name: cloud

x-backend-base: &backend-base
  env_file:
    - path: .env.common
      required: true
    - path: .env.local
      required: false
  environment:
    PGHOST: postgres
    PGUSER: /run/secrets/db_user
    PGPASSWORD: /run/secrets/db_password
    REDIS_URL: ${REDIS_URL:-redis://redis:6379}
    LOG_LEVEL: ${LOG_LEVEL:-info}

services:
  postgres:
    image: postgres:16-alpine
    networks:
      db-net:
        ipv4_address: 172.20.0.10
    mac_address: 02:42:ac:14:00:0a
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${POSTGRES_DB:?SEt env for POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_password
      - db_user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  backend_1:
    <<: *backend-base
    image: mikolajroot/backend:${APP_VERSION:-latest}
    networks:
      proxy-net:
        ipv4_address: 172.18.0.11
      app-net:
      db-net:
    environment:
      PORT: ${BACKEND_PORT_1:-3000}
    secrets:
      - db_password
      - db_user
    volumes:
      - backend_data:/app/persistent_data
    tmpfs: /app/tmp_data
    configs:
      - source: app_config
        target: /api/src/config.js
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  backend_2:
    <<: *backend-base
    image: mikolajroot/backend:${APP_VERSION:-latest}
    networks:
      proxy-net:
        ipv4_address: 172.18.0.12
      app-net:
      db-net:
    environment:
      PORT: ${BACKEND_PORT_2:-3001}
    secrets:
      - db_password
      - db_user
    volumes:
      - backend_data:/app/persistent_data
    tmpfs: /app/tmp_data
    configs:
      - source: app_config
        target: /api/src/config.js
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    <<: *backend-base
    image: mikolajroot/worker:${APP_VERSION:-latest}
    networks:
      - app-net
      - db-net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    secrets:
      - db_password
      - db_user

  nginx:
    image: mikolajroot/frontend:${APP_VERSION:-latest}
    networks:
      - proxy-net
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      backend_1:
        condition: service_started
      backend_2:
        condition: service_started

  adminer:
    image: adminer
    profiles: [debug]
    networks:
      - db-net

  pgadmin:
    image: dpage/pgadmin4
    profiles: [debug]
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - db-net

  db-migrator:
    image: alpine
    profiles: [migrate]
    restart: no
    networks:
      - db-net
    command: echo "Uruchamiam migrację bazy danych..." && sleep 2 && echo "Zakończono!"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  backend_data:
  redis_data:

networks:
  proxy-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
  app-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
  db-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

configs:
  nginx_config:
    file: ./frontend/nginx.conf
  app_config:
    file: ./backend/src/config.js

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_user:
    file: ./secrets/db_user.txt